[package]
name = "rupho"  # <-- This should match your Python import
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.24.2", features = ["extension-module"] }
numpy = "0.24.0"
ndarray = "0.16.1"
ndarray-npy = "0.9.1"
rayon = "1.5"
